name: fjordeco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - netcdf4
  - r-ggplot2
  - r-irkernel
  - r-ncdf4
  - r-raster
